export const queryKeys = {
  currentUser: ["currentUser"] as const,
  addresses: (query: string) => ["addresses", query] as const,
  savedPlaces: ["savedPlaces"] as const,
  fareEstimates: (pickupKey: string, dropKey: string, promo?: string) =>
    ["fareEstimates", pickupKey, dropKey, promo ?? null] as const,
  nearbyDrivers: (vehicleType: string) => ["nearbyDrivers", vehicleType] as const,
  activeRide: ["activeRide"] as const,
  rideStatus: (rideId: string) => ["rideStatus", rideId] as const,
  rideHistory: ["rideHistory"] as const,
  rideDetail: (rideId: string) => ["rideDetail", rideId] as const,
  wallet: ["wallet"] as const,
  paymentMethods: ["paymentMethods"] as const,

  currentDriver: ["currentDriver"] as const,
  kycDocuments: ["kycDocuments"] as const,
  verificationStatus: ["verificationStatus"] as const,
  dashboardSummary: ["dashboardSummary"] as const,
  incomingRequest: ["incomingRequest"] as const,
  activeDriverRide: ["activeDriverRide"] as const,
  driverRideHistory: ["driverRideHistory"] as const,
  driverEarnings: (period: string) => ["driverEarnings", period] as const,
  payoutHistory: ["payoutHistory"] as const,

  currentAdmin: ["currentAdmin"] as const,
  adminDashboard: ["adminDashboard"] as const,
  adminCustomers: (query: string) => ["adminCustomers", query] as const,
  adminCustomer: (id: string) => ["adminCustomer", id] as const,
  adminCustomerRides: (id: string) => ["adminCustomerRides", id] as const,
  adminCustomerWallet: (id: string) => ["adminCustomerWallet", id] as const,
  adminDrivers: (query: string) => ["adminDrivers", query] as const,
  adminDriver: (id: string) => ["adminDriver", id] as const,
  adminDriverKyc: (id: string) => ["adminDriverKyc", id] as const,
  adminDriverRides: (id: string) => ["adminDriverRides", id] as const,
  adminDriverEarnings: (id: string) => ["adminDriverEarnings", id] as const,
  adminRides: (query: string) => ["adminRides", query] as const,
  adminRide: (id: string) => ["adminRide", id] as const,
  adminWalletTransactions: (query: string) => ["adminWalletTransactions", query] as const,
  adminDriverEarningsList: (query: string) => ["adminDriverEarningsList", query] as const,
  adminRidesTrend: (period: string) => ["adminRidesTrend", period] as const,
  adminRevenueTrend: (period: string) => ["adminRevenueTrend", period] as const,
  adminPaymentSuccessRate: ["adminPaymentSuccessRate"] as const,
};
